// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
var SupplyChain = artifacts.require('SupplyChain')
const truffleAssert = require('truffle-assertions');

contract('SupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    var sku = 1
    var upc = 1
    const ownerID = accounts[0]
    const originFarmerID = accounts[1]
    const originFarmName = "John Doe"
    const originFarmInformation = "Yarray Valley"
    const originFarmLatitude = "-38.239770"
    const originFarmLongitude = "144.341490"
    var productID = sku + upc
    const productNotes = "Best beans for Espresso"
    const productPrice = web3.toWei(1, "ether")
    var itemState = 0
    const distributorID = accounts[2]
    const retailerID = accounts[3]
    const consumerID = accounts[4]
    const emptyAddress = '0x00000000000000000000000000000000000000'

    ///Available Accounts
    ///==================
    ///(0) 0x27d8d15cbc94527cadf5ec14b69519ae23288b95
    ///(1) 0x018c2dabef4904ecbd7118350a0c54dbeae3549a
    ///(2) 0xce5144391b4ab80668965f2cc4f2cc102380ef0a
    ///(3) 0x460c31107dd048e34971e57da2f99f659add4f02
    ///(4) 0xd37b7b8c62be2fdde8daa9816483aebdbd356088
    ///(5) 0x27f184bdc0e7a931b507ddd689d76dba10514bcb
    ///(6) 0xfe0df793060c49edca5ac9c104dd8e3375349978
    ///(7) 0xbd58a85c96cc6727859d853086fe8560bc137632
    ///(8) 0xe07b5ee5f738b2f87f88b99aac9c64ff1e0c7917
    ///(9) 0xbd3ff2e3aded055244d66544c9c059fa0851da44

    console.log("ganache-cli accounts used here...")
    console.log("Contract Owner: accounts[0] ", accounts[0])
    console.log("Farmer: accounts[1] ", accounts[1])
    console.log("Distributor: accounts[2] ", accounts[2])
    console.log("Retailer: accounts[3] ", accounts[3])
    console.log("Consumer: accounts[4] ", accounts[4])

    // 1st Test
    it("Testing smart contract function harvestItem() that allows a farmer to harvest coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        var eventEmitted = false
        
        // Watch the emitted event Harvested()
        var event = supplyChain.Harvested()
        await event.watch((err, res) => {
            eventEmitted = true
        })

        // Mark an item as Harvested by calling function harvestItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes)

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBufferOne[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferOne[2], ownerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferOne[3], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBufferOne[4], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBufferOne[5], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBufferOne[6], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBufferOne[7], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
        assert.equal(resultBufferTwo[5], 0, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')        
    });    

    // 2nd Test
    it("Testing smart contract function processItem() that allows a farmer to process coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        var eventEmitted = false;
        // Watch the emitted event Processed()
        var event = supplyChain.Processed();
        await event.watch((err,res)=>{
            eventEmitted = true;
        });
        // Mark an item as Processed by calling function processtItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        assert.equal(resultBufferTwo[5],0,"Error: the item state is not harvested");
       
        console.log("upc is "+upc);
        let result= await supplyChain.processItem(upc,{from:originFarmerID});

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
         resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc) 
        // Verify the result set
        truffleAssert.eventEmitted(result, 'Processed', (ev) => {
           return ev.upc==upc;
        });
        assert.equal(resultBufferTwo[5],1,"Error: the item state is not Processed");
    })    

    // 3rd Test
    it("Testing smart contract function packItem() that allows a farmer to pack coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        var event = supplyChain.Packed();
        
        // Watch the emitted event Packed()
        let eventEmitted = false;
        event.watch((err,res)=>{
            eventEmitted = true;
        });

        // Mark an item as Packed by calling function packItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        await supplyChain.processItem(upc,{from:originFarmerID});
      let result =  await supplyChain.packItem(upc,{from:originFarmerID});
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        // Verify the result set
        assert.equal(resultBufferTwo[5],2,"Error: the item state is not Packed");
        truffleAssert.eventEmitted(result, 'Packed', (ev) => {
         return ev.upc==upc;
      });
    })    

    // 4th Test
    it("Testing smart contract function sellItem() that allows a farmer to sell coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        let event  = supplyChain.ForSale();
        
        // Watch the emitted event ForSale()
        let eventEmitted = false;
        event.watch((err,res)=>{
            eventEmitted =  true;
        })

        // Mark an item as ForSale by calling function sellItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        let result = await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        // Verify the result set
        assert.equal(resultBufferTwo[5],3,"Error: the item state is not ForSale");
        truffleAssert.eventEmitted(result, 'ForSale', (ev) => {
         return ev.upc==upc;
      });
    })    

    // 5th Test
    it("Testing smart contract function buyItem() that allows a distributor to buy coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        let event = supplyChain.Sold()
        
        // Watch the emitted event Sold()
        let eventEmitted = false;
        event.watch((err,res)=>{
            eventEmitted = true;
        });
        // Mark an item as Sold by calling function buyItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});
        let result = await supplyChain.buyItem(upc,retailerID,{from:distributorID,value:productPrice});
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

        // Verify the result set
        assert.equal(resultBufferTwo[5],4,"Error: the item state is not yet sold");
        assert.equal(resultBufferTwo[6],distributorID,"Error: the expected distributor is not the distributor");
        assert.equal(resultBufferTwo[7],retailerID,"Error: the expected retailer is not the retailer");
        truffleAssert.eventEmitted(result, 'Sold', (ev) => {
         return ev.upc==upc;
      });
    })    

    // 6th Test
    it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        let event = supplyChain.Shipped();
        
        // Watch the emitted event Shipped()
        let eventEmitted = false;
        event.watch((err,res)=>{
            eventEmitted =true;
        })
        // Mark an item as shipped by calling function shipItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});
        await supplyChain.buyItem(upc,retailerID,{from:distributorID,value:productPrice});
        let result =  await supplyChain.shipItem(upc,consumerID,{from:retailerID});
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        // Verify the result set
        assert.equal(resultBufferTwo[5],5,"Error: the item state is not yet shipped");
        assert.equal(resultBufferTwo[8],consumerID,"Error: the item state is not yet shipped");
        truffleAssert.eventEmitted(result, 'Shipped', (ev) => {
         return ev.upc==upc;
      });
              
    })    

    // 7th Test
    it("Testing smart contract function receiveItem() that allows a retailer to mark coffee received", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        let event = supplyChain.Received();

        // Watch the emitted event Received()
        let eventEmitted = true;
        event.watch((err,res)=>{
            eventEmitted = true;
        });

        // Mark an item as Sold by calling function buyItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});
        await supplyChain.buyItem(upc,retailerID,{from:distributorID,value:productPrice});
        await supplyChain.shipItem(upc,consumerID,{from:retailerID});
        let result =   await supplyChain.receiveItem(upc,{from:retailerID});
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

        // Verify the result set
              // Verify the result set
        assert.equal(resultBufferTwo[5],6,"Error: the item state is not yet received");
        truffleAssert.eventEmitted(result, 'Received', (ev) => {
         return ev.upc==upc;
      });
    })    

    // 8th Test
    it("Testing smart contract function purchaseItem() that allows a consumer to purchase coffee", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        let event = supplyChain.Purchased();
        
        // Watch the emitted event Purchased()
        let eventEmitted = true;
        event.watch((err,res)=>{
            eventEmitted = true;
        });
        // Mark an item as Sold by calling function buyItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});
        await supplyChain.buyItem(upc,retailerID,{from:distributorID,value:productPrice});
        await supplyChain.shipItem(upc,consumerID,{from:retailerID});
        await supplyChain.receiveItem(upc,{from:retailerID});
        let result = await supplyChain.purchaseItem(upc,{from:consumerID});
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

        // Verify the result set
        assert.equal(resultBufferTwo[5],7,"Error: the item state is not yet purchased");
        truffleAssert.eventEmitted(result, 'Purchased', (ev) => {
         return ev.upc==upc;
      });
    })    

    // 9th Test
    it("Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain", async() => {
        const supplyChain = await SupplyChain.deployed()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});
        await supplyChain.buyItem(upc,retailerID,{from:distributorID,value:productPrice});
        await supplyChain.shipItem(upc,consumerID,{from:retailerID});
        await supplyChain.receiveItem(upc,{from:retailerID});
        let result = await supplyChain.purchaseItem(upc,{from:consumerID});
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);
        // Verify the result set:
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        console.log(Number(resultBufferOne[0]));
        assert.equal(resultBufferOne[0], 9, 'Error: Invalid item SKU')
        assert.equal(resultBufferOne[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferOne[2], ownerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferOne[3], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBufferOne[4], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBufferOne[5], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBufferOne[6], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBufferOne[7], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
       
    })

    // 10th Test
    it("Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        await supplyChain.harvestItem(upc, originFarmerID, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, productNotes,{from:originFarmerID});
        await supplyChain.processItem(upc,{from:originFarmerID});
        await supplyChain.packItem(upc,{from:originFarmerID});
        await supplyChain.sellItem(upc,productPrice,{from:originFarmerID});
        await supplyChain.buyItem(upc,retailerID,{from:distributorID,value:productPrice});
        await supplyChain.shipItem(upc,consumerID,{from:retailerID});
        await supplyChain.receiveItem(upc,{from:retailerID});
        let result = await supplyChain.purchaseItem(upc,{from:consumerID});
        
        // Verify the result set:
        let resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

        assert.equal(resultBufferTwo[0],10,'Error: Invalid item SKU');
        assert.equal(resultBufferTwo[1],upc,'Error: Invalid item UPC');
        assert.equal(resultBufferTwo[2],10+upc,"'Error: Invalid item Productid'");
        assert.equal(resultBufferTwo[3],productNotes,"Error: the item state is not yet shipped");
        assert.equal(resultBufferTwo[4],productPrice,"Error: the item state is not yet shipped");
        assert.equal(resultBufferTwo[5],7,"Error: the item state is not yet purchased");
        assert.equal(resultBufferTwo[6],distributorID,"Error: the expected distributor is not the distributor");
        assert.equal(resultBufferTwo[7],retailerID,"Error: the expected retailer is not the retailer");
        assert.equal(resultBufferTwo[8],consumerID,"Error: the consumer is not the expected consumer");
      
    })

});

